# Generated by Django 6.0.5 on 2026-05-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='number',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
