# Generated by Django 6.0.5 on 2026-05-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0002_alter_students_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
