# Generated by Django 6.0.5 on 2026-05-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('number', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
