# Generated by Django 6.0.5 on 2026-05-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_alter_teacher_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
