# Generated by Django 6.0.5 on 2026-05-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0003_alter_teacher_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
